sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true PHPUNIT_VERSION=^6
  - AMP_DEBUG=true PHPUNIT_VERSION=^7
  - AMP_DEBUG=true PHPUNIT_VERSION=^8

install:
  - composer update -n --prefer-dist
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar
  - chmod +x coveralls.phar
  - composer require phpunit/phpunit:${PHPUNIT_VERSION}

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - ./coveralls.phar -v

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.php-cs-fixer
